# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MisionMujer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MisionMujer

  pod 'Alamofire', '4.4.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SDWebImage', '~> 4.0'

  target 'MisionMujerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MisionMujerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
